/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.company.view;

import com.company.Controller.Control;
import com.company.model.FileOperations;
import com.company.model.Invoice_Header;
import com.company.model.Invoice_Line;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Ahmed
 */
public class UIPanel extends javax.swing.JPanel {

    /**
     * Creates new form UIPanel
     */
    String[] H_Cols = {"No.","Date","Customer","Total"};
    String[] L_Cols = {"No.","Item Name","Item Price","Count","Item Total"};
    public static int clicked_Header_row = -1 ;
    public static int clicked_Line_row = -1 ;
    
    public UIPanel() {
        initComponents();
        String[][] H_Data = Control.get_Header_data();
        
        
        
        Inv_H_Table.setModel(new javax.swing.table.DefaultTableModel(
            H_Data,
            H_Cols));
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Inv_H_Table = new javax.swing.JTable();
        new_item_btn = new javax.swing.JButton();
        del_item_btn = new javax.swing.JButton();
        Create_Invoice_Btn = new javax.swing.JButton();
        Delete_btn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Inv_L_Table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        invoice_num_val = new javax.swing.JLabel();
        Invoice_total_val = new javax.swing.JLabel();
        Date_TF = new javax.swing.JTextField();
        Cust_TF = new javax.swing.JTextField();
        save_btn = new javax.swing.JButton();

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        Inv_H_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Date", "Customer", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Inv_H_Table.setInheritsPopupMenu(true);
        Inv_H_Table.getTableHeader().setReorderingAllowed(false);
        Inv_H_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inv_H_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Inv_H_Table);

        new_item_btn.setActionCommand("Save");
        new_item_btn.setLabel("Create Item");
        new_item_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_item_btnActionPerformed(evt);
            }
        });

        del_item_btn.setActionCommand("h");
        del_item_btn.setLabel("Delete Item");
        del_item_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_item_btnActionPerformed(evt);
            }
        });

        Create_Invoice_Btn.setLabel("Create New Invoice");
        Create_Invoice_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_Invoice_BtnActionPerformed(evt);
            }
        });

        Delete_btn.setLabel("Delete Invoice");
        Delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btnActionPerformed(evt);
            }
        });

        Inv_L_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "Item Name", "Item Price", "Count", "Item Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Inv_L_Table.getTableHeader().setReorderingAllowed(false);
        Inv_L_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inv_L_TableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Inv_L_Table);
        if (Inv_L_Table.getColumnModel().getColumnCount() > 0) {
            Inv_L_Table.getColumnModel().getColumn(3).setResizable(false);
            Inv_L_Table.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setText("Invoice Number");

        jLabel2.setText("Invoice Date");

        jLabel3.setText("Customer Name");
        jLabel3.setToolTipText("");

        jLabel4.setText("Invoice Total");

        invoice_num_val.setText("Invoice Total");

        Invoice_total_val.setText("Invoice Total value");

        Date_TF.setToolTipText("");
        Date_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Date_TFActionPerformed(evt);
            }
        });

        Cust_TF.setToolTipText("");

        save_btn.setActionCommand("Save");
        save_btn.setLabel("Save Cahnges");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(Create_Invoice_Btn)
                .addGap(68, 68, 68)
                .addComponent(Delete_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(new_item_btn)
                .addGap(18, 18, 18)
                .addComponent(del_item_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Invoice_total_val)
                            .addComponent(invoice_num_val)
                            .addComponent(Date_TF, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(Cust_TF))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(invoice_num_val))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Date_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(Cust_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Invoice_total_val))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(save_btn)
                            .addComponent(del_item_btn)
                            .addComponent(new_item_btn))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Create_Invoice_Btn)
                            .addComponent(Delete_btn))
                        .addGap(18, 18, 18))))
        );

        new_item_btn.getAccessibleContext().setAccessibleName("Save");
        invoice_num_val.getAccessibleContext().setAccessibleName("Invoice number value");

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void new_item_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_item_btnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Inv_L_Table.getModel();
        model.addRow(new Object[]{clicked_Header_row, "def_item", "1" , "1" , "1"});
        String [] line_data = {"def_item", "1" , "1"};
        Control.add_line_into_selected_inv(clicked_Header_row, "def_item", 1 , 1);
        
    }//GEN-LAST:event_new_item_btnActionPerformed

    private void del_item_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_item_btnActionPerformed
        if(clicked_Line_row == -1 ||clicked_Header_row == -1 )
        {
            return;
        }
        else{
        
            DefaultTableModel model = (DefaultTableModel) Inv_L_Table.getModel();
model.removeRow(clicked_Line_row);
Control.delete_line_from_selected_inv(clicked_Header_row, clicked_Line_row);
clicked_Line_row = -1;
clicked_Header_row = -1;
Inv_H_Table.clearSelection();
Inv_L_Table.clearSelection();
        }
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_del_item_btnActionPerformed

    private void Inv_H_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inv_H_TableMouseClicked
        // TODO add your handling code here:
         JTable source;
        source = (JTable)evt.getSource();
        clicked_Line_row = -1;
            clicked_Header_row = Inv_H_Table.getSelectedRow();
            int column;
        column = Inv_H_Table.getSelectedColumn()+1;
            int index =  Integer.valueOf(Inv_H_Table.getModel().getValueAt(clicked_Header_row, 0).toString());
            clicked_Header_row = index;
            String Data[][] = Control.get_Lines_data(clicked_Header_row);
            Inv_L_Table.setModel(new javax.swing.table.DefaultTableModel(
            Data,
            L_Cols));

            
            

            String[] selected_Inv_data= new String[4];
            selected_Inv_data = Control.get_Selected_Invoice_data(clicked_Header_row);
            
            invoice_num_val.setText(selected_Inv_data[0]);
            Date_TF.setText(selected_Inv_data[1]);
            Cust_TF.setText(selected_Inv_data[2]);
            Invoice_total_val.setText(selected_Inv_data[3]);
    }//GEN-LAST:event_Inv_H_TableMouseClicked

    private void Date_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Date_TFActionPerformed
                    
    }//GEN-LAST:event_Date_TFActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
         SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy", Locale.ENGLISH);

                Date date = null;
                try {
                    date = formatter.parse(Date_TF.getText());
                    Control.update_Date_and_Customer(clicked_Header_row, date, Cust_TF.getText());
                } catch (ParseException e) {
                    JOptionPane.showMessageDialog(null, "wromg date format", "wromg date format", JOptionPane.WARNING_MESSAGE);
                } 
                
                String[][] H_Data = Control.get_Header_data();
        
        
        
        Inv_H_Table.setModel(new javax.swing.table.DefaultTableModel(
            H_Data,
            H_Cols));
        Inv_H_Table.clearSelection();
        Inv_L_Table.clearSelection();
       
    }//GEN-LAST:event_save_btnActionPerformed

    private void Inv_L_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inv_L_TableMouseClicked
        clicked_Line_row = Inv_L_Table.getSelectedRow();        // TODO add your handling code here:
    }//GEN-LAST:event_Inv_L_TableMouseClicked

    private void Create_Invoice_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_Invoice_BtnActionPerformed
        int x = FileOperations.getInv_H_count();
        
        DefaultTableModel model = (DefaultTableModel) Inv_H_Table.getModel();
        model.addRow(new Object[]{x+1, "01-01-2022", "Def Customer" , "1"});
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy", Locale.ENGLISH);

                Date date = null;
                try {
                    date = formatter.parse("01-01-2022");
                } catch (ParseException e) {
                    //wrong date format
                }
        Invoice_Header inv_H = new Invoice_Header(x+1, date, "Def Customer");
        Invoice_Line Line = new Invoice_Line(inv_H ,"Def Item", 1, 1);
        inv_H.add_Line(Line);
        FileOperations.getInv_H().add(inv_H);
        
        clicked_Header_row = -1;
        clicked_Line_row = -1;
        Inv_H_Table.clearSelection();
        Inv_L_Table.clearSelection();
        FileOperations.setInv_H_count(x+1);

// TODO add your handling code here:
    }//GEN-LAST:event_Create_Invoice_BtnActionPerformed

    private void Delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btnActionPerformed
      if(clicked_Header_row == -1 )
        {
            return;
        }
        else{
        
            DefaultTableModel model = (DefaultTableModel) Inv_H_Table.getModel();
            model.removeRow(clicked_Header_row-1);
            FileOperations.getInv_H().remove(clicked_Header_row-1);
            clicked_Line_row = -1;
            clicked_Header_row = -1;
            Inv_H_Table.clearSelection();
            Inv_L_Table.clearSelection();
        }        // TODO add your handling code here:
        
    }//GEN-LAST:event_Delete_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Create_Invoice_Btn;
    private javax.swing.JTextField Cust_TF;
    private javax.swing.JTextField Date_TF;
    private javax.swing.JButton Delete_btn;
    private javax.swing.JTable Inv_H_Table;
    private javax.swing.JTable Inv_L_Table;
    private javax.swing.JLabel Invoice_total_val;
    private javax.swing.JButton del_item_btn;
    private javax.swing.JLabel invoice_num_val;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton new_item_btn;
    private javax.swing.JButton save_btn;
    // End of variables declaration//GEN-END:variables
}
